// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMaYXQoTOxp2AmPfNGDeYjjw36_GCJoBk',
    appId: '1:809075074588:web:34f9fbc0cdfee4df62e1d9',
    messagingSenderId: '809075074588',
    projectId: 'weatherit-1b791',
    authDomain: 'weatherit-1b791.firebaseapp.com',
    storageBucket: 'weatherit-1b791.appspot.com',
    measurementId: 'G-EXEBSGRXWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCct3GLlXT8zIAaNovmgK7XyUUqS-izH0k',
    appId: '1:809075074588:android:cf07900b80c3e96562e1d9',
    messagingSenderId: '809075074588',
    projectId: 'weatherit-1b791',
    storageBucket: 'weatherit-1b791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQuF7580tSESQM_W2XzyTEt0d52SvqD8',
    appId: '1:809075074588:ios:7746386f4c36572962e1d9',
    messagingSenderId: '809075074588',
    projectId: 'weatherit-1b791',
    storageBucket: 'weatherit-1b791.appspot.com',
    iosBundleId: 'com.example.weatherit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQuF7580tSESQM_W2XzyTEt0d52SvqD8',
    appId: '1:809075074588:ios:7746386f4c36572962e1d9',
    messagingSenderId: '809075074588',
    projectId: 'weatherit-1b791',
    storageBucket: 'weatherit-1b791.appspot.com',
    iosBundleId: 'com.example.weatherit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMaYXQoTOxp2AmPfNGDeYjjw36_GCJoBk',
    appId: '1:809075074588:web:9242e301d3ad471762e1d9',
    messagingSenderId: '809075074588',
    projectId: 'weatherit-1b791',
    authDomain: 'weatherit-1b791.firebaseapp.com',
    storageBucket: 'weatherit-1b791.appspot.com',
    measurementId: 'G-S7XRS47BML',
  );
}
